# Generated by Django 4.1.1 on 2022-10-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_alter_pedido_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data',
        ),
    ]
